# Generated by Django 6.0.5 on 2026-05-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, help_text='進行中の Stripe Checkout Session ID', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='stripe_connect_account_id',
            field=models.CharField(blank=True, help_text='acct_ で始まる Connect アカウントID（出品者の受取先）', max_length=255, verbose_name='Stripe Connect アカウントID'),
        ),
    ]
