# Generated by Django 6.0.5 on 2026-05-15 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_buyer_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='course_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='授業名'),
        ),
        migrations.AddField(
            model_name='product',
            name='professor_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='教授名'),
        ),
        migrations.CreateModel(
            name='TradeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=200)),
                ('is_preset', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_messages', to='app.product')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(blank=True, choices=[('政治経済学部', '政治経済学部'), ('法学部', '法学部'), ('商学部', '商学部'), ('教育学部', '教育学部'), ('文学部', '文学部'), ('文化構想学部', '文化構想学部')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
