# Generated by Django 6.0.5 on 2026-05-15 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_board_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='godbuttonuse',
            name='thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='god_uses', to='app.coursethread'),
        ),
        migrations.CreateModel(
            name='TimelinePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=280)),
                ('course_name', models.CharField(max_length=120)),
                ('professor_name', models.CharField(blank=True, max_length=120)),
                ('faculty', models.CharField(blank=True, choices=[('政治経済学部', '政治経済学部'), ('法学部', '法学部'), ('商学部', '商学部'), ('教育学部', '教育学部'), ('文学部', '文学部'), ('文化構想学部', '文化構想学部')], max_length=50)),
                ('god_count', models.PositiveIntegerField(default=0)),
                ('tip_total', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='godbuttonuse',
            name='timeline_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='god_uses', to='app.timelinepost'),
        ),
        migrations.CreateModel(
            name='TimelineTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeline_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tips', to='app.timelinepost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
