# Generated by Django 6.0.5 on 2026-06-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_devicepushtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_removed",
            field=models.BooleanField(db_index=True, default=False, verbose_name="運営削除"),
        ),
        migrations.AddField(
            model_name="comment",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="削除日時"),
        ),
        migrations.AddField(
            model_name="comment",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_removed",
            field=models.BooleanField(db_index=True, default=False, verbose_name="運営削除"),
        ),
        migrations.AddField(
            model_name="product",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="削除日時"),
        ),
        migrations.AddField(
            model_name="product",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="timelinepost",
            name="is_removed",
            field=models.BooleanField(db_index=True, default=False, verbose_name="運営削除"),
        ),
        migrations.AddField(
            model_name="timelinepost",
            name="removed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="削除日時"),
        ),
        migrations.AddField(
            model_name="timelinepost",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="removed_timeline_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ContentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("post", "タイムライン投稿"),
                            ("comment", "コメント"),
                            ("user", "ユーザー"),
                            ("product", "出品"),
                        ],
                        max_length=16,
                        verbose_name="対象種別",
                    ),
                ),
                ("target_id", models.PositiveIntegerField(verbose_name="対象ID")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "スパム・宣伝"),
                            ("harassment", "嫌がらせ・誹謗中傷"),
                            ("inappropriate", "不適切な内容"),
                            ("fraud", "詐欺・虚偽出品"),
                            ("other", "その他"),
                        ],
                        max_length=32,
                        verbose_name="理由",
                    ),
                ),
                ("detail", models.TextField(blank=True, verbose_name="詳細")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_reports_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "blocker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks_initiated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="contentreport",
            constraint=models.UniqueConstraint(
                fields=("reporter", "target_type", "target_id"),
                name="unique_content_report_per_user_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="userblock",
            constraint=models.UniqueConstraint(
                fields=("blocker", "blocked"),
                name="unique_user_block",
            ),
        ),
    ]
