# Generated by Django 6.0.5 on 2026-05-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_comment_author_comment_timeline_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='faculty',
            field=models.CharField(blank=True, choices=[('政治経済学部', '政治経済学部'), ('法学部', '法学部'), ('教育学部', '教育学部'), ('商学部', '商学部'), ('社会科学部', '社会科学部'), ('国際教養学部', '国際教養学部'), ('文化構想学部', '文化構想学部'), ('文学部', '文学部'), ('基幹理工学部', '基幹理工学部'), ('創造理工学部', '創造理工学部'), ('先進理工学部', '先進理工学部'), ('人間科学部', '人間科学部'), ('スポーツ科学部', 'スポーツ科学部'), ('その他', 'その他')], max_length=50),
        ),
        migrations.AlterField(
            model_name='coursethread',
            name='faculty',
            field=models.CharField(blank=True, choices=[('政治経済学部', '政治経済学部'), ('法学部', '法学部'), ('教育学部', '教育学部'), ('商学部', '商学部'), ('社会科学部', '社会科学部'), ('国際教養学部', '国際教養学部'), ('文化構想学部', '文化構想学部'), ('文学部', '文学部'), ('基幹理工学部', '基幹理工学部'), ('創造理工学部', '創造理工学部'), ('先進理工学部', '先進理工学部'), ('人間科学部', '人間科学部'), ('スポーツ科学部', 'スポーツ科学部'), ('その他', 'その他')], max_length=50),
        ),
        migrations.AlterField(
            model_name='timelinepost',
            name='faculty',
            field=models.CharField(blank=True, choices=[('政治経済学部', '政治経済学部'), ('法学部', '法学部'), ('教育学部', '教育学部'), ('商学部', '商学部'), ('社会科学部', '社会科学部'), ('国際教養学部', '国際教養学部'), ('文化構想学部', '文化構想学部'), ('文学部', '文学部'), ('基幹理工学部', '基幹理工学部'), ('創造理工学部', '創造理工学部'), ('先進理工学部', '先進理工学部'), ('人間科学部', '人間科学部'), ('スポーツ科学部', 'スポーツ科学部'), ('その他', 'その他')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='faculty',
            field=models.CharField(blank=True, choices=[('政治経済学部', '政治経済学部'), ('法学部', '法学部'), ('教育学部', '教育学部'), ('商学部', '商学部'), ('社会科学部', '社会科学部'), ('国際教養学部', '国際教養学部'), ('文化構想学部', '文化構想学部'), ('文学部', '文学部'), ('基幹理工学部', '基幹理工学部'), ('創造理工学部', '創造理工学部'), ('先進理工学部', '先進理工学部'), ('人間科学部', '人間科学部'), ('スポーツ科学部', 'スポーツ科学部'), ('その他', 'その他')], max_length=50),
        ),
    ]
