# Generated by Django 6.0.5 on 2026-05-17 08:52

from django.db import migrations, models


def migrate_sold_status(apps, schema_editor):
    Product = apps.get_model("app", "Product")
    Product.objects.filter(status="sold").update(
        status="sold_out",
        seller_trade_completed=True,
        buyer_trade_completed=True,
    )


def reverse_sold_status(apps, schema_editor):
    Product = apps.get_model("app", "Product")
    Product.objects.filter(status="sold_out").update(status="sold")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_product_faculty_alter_coursethread_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyer_trade_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='seller_trade_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(migrate_sold_status, reverse_sold_status),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', '出品中'), ('trading', '取引中'), ('sold_out', '売り切れ')], default='available', max_length=20),
        ),
    ]
