# Generated by Django 6.0.5 on 2026-05-19 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_user_managers_signupotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', verbose_name='画像'),
        ),
    ]
