# Generated by Django 6.0.5 on 2026-07-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_drop_orphan_timelinepost_tip_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='プロフィール画像'),
        ),
    ]
