# Generated by Django 6.0.5 on 2026-08-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_ensure_chatroom_group_chat_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_timetable_public',
            field=models.BooleanField(default=False, help_text='true のとき他ユーザーのプロフィールから時間割を閲覧できる。', verbose_name='時間割を公開する'),
        ),
    ]
