# Generated by Django 6.0.5 on 2026-08-02 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_ensure_userprofile_is_timetable_public_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_key', models.CharField(help_text='例: p1-d0（月曜1限）, od1-d2（水曜OD1）', max_length=16, verbose_name='スロットキー')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='授業名')),
                ('room', models.CharField(blank=True, max_length=80, verbose_name='教室')),
                ('credits', models.CharField(blank=True, max_length=20, verbose_name='単位')),
                ('memo', models.TextField(blank=True, verbose_name='進捗・課題メモ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '時間割スロット',
                'verbose_name_plural': '時間割スロット',
                'ordering': ['slot_key'],
                'constraints': [models.UniqueConstraint(fields=('user', 'slot_key'), name='unique_timetable_slot_per_user')],
            },
        ),
    ]
