# Generated by Django 6.0.5 on 2026-08-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_ensure_timetable_slot_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='handover_campus',
            field=models.CharField(blank=True, choices=[('waseda', '早稲田キャンパス'), ('toyama', '戸山キャンパス'), ('nishi_waseda', '西早稲田キャンパス'), ('tokorozawa', '所沢キャンパス'), ('other', 'その他・要相談')], db_index=True, default='', max_length=32, verbose_name='受け渡しキャンパス'),
        ),
    ]
