# Generated by Django 6.0.5 on 2026-08-09 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_user_username_lower_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoomInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '招待中'), ('accepted', '参加済み'), ('declined', '辞退')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_invitations_received', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='app.chatroom')),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('room', 'invitee'), name='unique_chat_room_invitation_per_invitee'), models.CheckConstraint(condition=models.Q(('inviter', models.F('invitee')), _negated=True), name='chat_room_invitation_no_self')],
            },
        ),
    ]
