# Generated by Django 6.0.5 on 2026-08-09 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_chatroom_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDirectMessageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'リクエスト中'), ('accepted', '承認済み'), ('declined', '拒否')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_requests', to='app.userdirectmessageroom')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dm_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('room', 'to_user'), name='unique_dm_request_per_room_recipient'), models.CheckConstraint(condition=models.Q(('from_user', models.F('to_user')), _negated=True), name='dm_request_no_self')],
            },
        ),
    ]
