# Generated by Django 6.1 on 2026-08-17 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_calendar_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='授業名')),
                ('title_normalized', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='正規化授業名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '授業',
                'verbose_name_plural': '授業',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('current', '履修中'), ('past', '過去履修')], db_index=True, default='current', max_length=16, verbose_name='役割')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '履修',
                'verbose_name_plural': '履修',
            },
        ),
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveIntegerField(db_index=True, verbose_name='年度')),
                ('semester', models.CharField(choices=[('spring', '春学期'), ('fall', '秋学期'), ('full', '通年')], db_index=True, max_length=16, verbose_name='学期')),
                ('title', models.CharField(max_length=120, verbose_name='授業名')),
                ('title_normalized', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='正規化授業名')),
                ('instructor', models.CharField(max_length=120, verbose_name='担当教員')),
                ('instructor_normalized', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='正規化教員名')),
                ('day_of_week', models.PositiveSmallIntegerField(help_text='0=月 … 5=土', verbose_name='曜日')),
                ('period_kind', models.CharField(choices=[('period', '通常限'), ('od', 'オンデマンド')], default='period', max_length=16, verbose_name='時限種別')),
                ('period', models.PositiveSmallIntegerField(verbose_name='時限')),
                ('school', models.CharField(blank=True, max_length=50, verbose_name='学部')),
                ('campus', models.CharField(blank=True, max_length=40, verbose_name='キャンパス')),
                ('room', models.CharField(blank=True, max_length=80, verbose_name='教室')),
                ('credits', models.CharField(blank=True, max_length=20, verbose_name='単位')),
                ('source', models.CharField(choices=[('user', 'ユーザー'), ('admin', '管理者')], default='user', max_length=16, verbose_name='出典')),
                ('status', models.CharField(choices=[('active', '有効'), ('merged', '統合済み')], db_index=True, default='active', max_length=16, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '開講授業',
                'verbose_name_plural': '開講授業',
                'ordering': ['title', 'day_of_week', 'period'],
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveSmallIntegerField(verbose_name='総合評価')),
                ('difficulty_rating', models.PositiveSmallIntegerField(verbose_name='単位取得難易度')),
                ('workload_rating', models.PositiveSmallIntegerField(verbose_name='課題量')),
                ('attendance_rating', models.PositiveSmallIntegerField(verbose_name='出席重要度')),
                ('exam_rating', models.PositiveSmallIntegerField(verbose_name='試験')),
                ('comment', models.TextField(blank=True, max_length=1000, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '授業レビュー',
                'verbose_name_plural': '授業レビュー',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='app.course', verbose_name='授業'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_offerings_created', to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='app.courseoffering', verbose_name='統合先'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app.courseoffering', verbose_name='開講授業'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_slots', to='app.courseoffering', verbose_name='開講授業'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.courseoffering', verbose_name='開講授業'),
        ),
        migrations.AddField(
            model_name='coursereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['status', 'title_normalized', 'instructor_normalized'], name='app_courseo_status_2d5af9_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['status', 'day_of_week', 'period_kind', 'period'], name='app_courseo_status_8ae37d_idx'),
        ),
        migrations.AddIndex(
            model_name='courseoffering',
            index=models.Index(fields=['academic_year', 'semester', 'status'], name='app_courseo_academi_201d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['offering', 'role'], name='app_coursee_offerin_d2d8d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('user', 'offering'), name='unique_course_enrollment_per_user'),
        ),
        migrations.AddConstraint(
            model_name='coursereview',
            constraint=models.UniqueConstraint(fields=('user', 'offering'), name='unique_course_review_per_user'),
        ),
    ]
