# Generated by Django 6.1 on 2026-08-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_course_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='モデレーションにより一覧から隠す', verbose_name='非表示'),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='target_type',
            field=models.CharField(choices=[('post', 'タイムライン投稿'), ('comment', 'コメント'), ('user', 'ユーザー'), ('product', '出品'), ('course_offering', '開講授業'), ('course_review', '授業レビュー')], max_length=16, verbose_name='対象種別'),
        ),
        migrations.AlterField(
            model_name='courseoffering',
            name='status',
            field=models.CharField(choices=[('active', '有効'), ('merged', '統合済み'), ('hidden', '非表示')], db_index=True, default='active', max_length=16, verbose_name='状態'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('title_normalized',), name='unique_course_title_normalized'),
        ),
        migrations.AddConstraint(
            model_name='courseoffering',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('title_normalized', 'instructor_normalized', 'academic_year', 'semester', 'day_of_week', 'period_kind', 'period'), name='uniq_active_course_offering_identity'),
        ),
    ]
