# Generated by Django 6.1 on 2026-08-20 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_course_layer_hardening'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_hidden',
            field=models.BooleanField(db_index=True, default=False, help_text='モデレーションにより一覧から隠す', verbose_name='非表示'),
        ),
        migrations.AddField(
            model_name='courseoffering',
            name='chat_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_offering', to='app.chatroom', verbose_name='授業トーク'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='kind',
            field=models.CharField(choices=[('product', '商品チャット'), ('group', 'グループチャット'), ('course', '授業トーク')], db_index=True, default='product', max_length=20),
        ),
        migrations.AlterField(
            model_name='contentreport',
            name='target_type',
            field=models.CharField(choices=[('post', 'タイムライン投稿'), ('comment', 'コメント'), ('user', 'ユーザー'), ('product', '出品'), ('course_offering', '開講授業'), ('course_review', '授業レビュー'), ('chat_message', 'チャットメッセージ')], max_length=16, verbose_name='対象種別'),
        ),
    ]
