# Generated by Django 6.1

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_course_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='送信者によるソフト削除。モデレーションの is_hidden とは別。', null=True, verbose_name='ユーザー削除日時'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='app.chatmessage', verbose_name='返信先'),
        ),
    ]
