# Generated by Django 6.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0048_chat_message_reply_delete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCalendarException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="対象日")),
                (
                    "status",
                    models.CharField(
                        choices=[("skipped", "非表示")],
                        db_index=True,
                        default="skipped",
                        max_length=20,
                        verbose_name="状態",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_exceptions",
                        to="app.courseoffering",
                        verbose_name="開講授業",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_calendar_exceptions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザー",
                    ),
                ),
            ],
            options={
                "verbose_name": "授業カレンダー例外",
                "verbose_name_plural": "授業カレンダー例外",
                "ordering": ["-date", "-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="coursecalendarexception",
            index=models.Index(
                fields=["user", "date"], name="app_cce_user_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursecalendarexception",
            index=models.Index(
                fields=["user", "status"], name="app_cce_user_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecalendarexception",
            constraint=models.UniqueConstraint(
                fields=("user", "offering", "date"),
                name="unique_course_calendar_exception_per_day",
            ),
        ),
    ]
