# Generated by Django 6.1.1 on 2026-09-16 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_affiliated_school_faculty"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="removed_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="運営が非表示にした日時。",
                null=True,
                verbose_name="運営削除日時",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="removed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="運営削除を実行したスタッフ。",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_messages_removed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="removal_reason",
            field=models.CharField(
                blank=True,
                help_text="一般ユーザーには出さない。",
                max_length=200,
                verbose_name="運営内部用の削除理由",
            ),
        ),
        migrations.AlterField(
            model_name="chatmessage",
            name="is_hidden",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="運営モデレーションによりチャット上をプレースホルダ表示にする。元本文は DB に残す。",
                verbose_name="非表示",
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="handled_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="運営が対象コンテンツを対応済みにした日時。未対応は空。",
                null=True,
                verbose_name="対応日時",
            ),
        ),
        migrations.AddField(
            model_name="contentreport",
            name="handled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="content_reports_handled",
                to=settings.AUTH_USER_MODEL,
                verbose_name="対応者",
            ),
        ),
        migrations.CreateModel(
            name="ChatMessageModerationAppeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(max_length=1000, verbose_name="申立理由"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "確認中"),
                            ("accepted", "認容（復元）"),
                            ("rejected", "却下"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                        verbose_name="状態",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="申立日時"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="審査日時"
                    ),
                ),
                ("review_note", models.TextField(blank=True, verbose_name="運営メモ")),
                (
                    "appellant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_message_moderation_appeals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申立人",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_appeals",
                        to="app.chatmessage",
                        verbose_name="対象メッセージ",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_message_appeals_reviewed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="審査者",
                    ),
                ),
            ],
            options={
                "verbose_name": "チャットメッセージ異議申し立て",
                "verbose_name_plural": "チャットメッセージ異議申し立て",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="chatmessagemoderationappeal",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("message", "appellant"),
                name="uniq_pending_chatmsg_moderation_appeal",
            ),
        ),
    ]
