# Generated by Django 6.1.1 on 2026-09-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0057_chat_message_moderation_appeal"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdirectmessage",
            name="message_kind",
            field=models.CharField(
                choices=[("text", "テキスト"), ("share", "シェア")],
                db_index=True,
                default="text",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="userdirectmessage",
            name="share_target_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userdirectmessage",
            name="share_target_type",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddConstraint(
            model_name="userdirectmessage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("message_kind", "text"),
                    models.Q(
                        ("message_kind", "share"),
                        ("share_target_type__in", ["timeline", "flea"]),
                        ("share_target_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="dm_share_target_required",
            ),
        ),
    ]
