# Generated by Django 6.1.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0058_dm_share_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contentreport",
            name="target_type",
            field=models.CharField(
                choices=[
                    ("post", "タイムライン投稿"),
                    ("comment", "コメント"),
                    ("user", "ユーザー"),
                    ("product", "出品"),
                    ("course_offering", "開講授業"),
                    ("course_review", "授業レビュー"),
                    ("chat_message", "チャットメッセージ"),
                    ("community_thread", "コミュニティ投稿"),
                    ("community_reply", "コミュニティ返信"),
                ],
                max_length=16,
                verbose_name="対象種別",
            ),
        ),
    ]
