"""
Django settings for wasewase project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import ssl
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

from .email_env import (
    EMAIL_ENV_WARNINGS,
    WASE_USE_BUILTIN_GMAIL,
    is_ascii_only,
    load_sanitized_email_env,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env(name: str, default: str = "") -> str:
    """環境変数を読み込み、前後の空白を除去する。"""
    value = os.environ.get(name, default)
    if value is None:
        return ""
    return str(value).strip()


def _env_bool(name: str, default: bool = False) -> bool:
    raw = _env(name, "")
    if not raw:
        return default
    return raw.lower() in ("1", "true", "yes", "on")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", default=True)

# SECURITY WARNING: keep the secret key used in production secret!
_secret_key = _env("DJANGO_SECRET_KEY", "")
if _secret_key:
    SECRET_KEY = _secret_key
elif DEBUG:
    SECRET_KEY = "django-insecure-n6!_=099v4ai4w#a=h^lvsflew4u7ylh%_bb&7+(7g(cstkpk9"
else:
    raise ImproperlyConfigured(
        "本番では環境変数 DJANGO_SECRET_KEY を設定してください。"
    )

_allowed_hosts = _env("DJANGO_ALLOWED_HOSTS", "")
if _allowed_hosts:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(",") if h.strip()]
elif DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
else:
    ALLOWED_HOSTS = []

_csrf_origins = _env("DJANGO_CSRF_TRUSTED_ORIGINS", "")
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [
        o.strip() for o in _csrf_origins.split(",") if o.strip()
    ]


# Application definition

AUTH_USER_MODEL = "app.User"

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wasewase.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.notification_badge',
            ],
        },
    },
]

WSGI_APPLICATION = 'wasewase.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_database_url = _env("DATABASE_URL", "")
if _database_url:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            default=_database_url,
            conn_max_age=600,
            ssl_require=_env_bool("DATABASE_SSL_REQUIRE", default=False),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Media files (uploaded images)
MEDIA_URL = '/media/'
_media_root = _env("MEDIA_ROOT", "")
MEDIA_ROOT = Path(_media_root) if _media_root else BASE_DIR / 'media'

# 本番でアップロード画像を Django から配信する（Render 等の単一サーバー向け）
# 外部ストレージ利用時は環境変数 SERVE_MEDIA=false にしてください。
SERVE_MEDIA = _env_bool("SERVE_MEDIA", default=True)

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", default=False)

# ---------------------------------------------------------------------------
# メール（Gmail SMTP）
# wasewase/email_env.py の組み込み設定（wasewaseofficial@gmail.com）が最優先。
# 環境変数 WASE_* は組み込み無効時のみ使用。
# ---------------------------------------------------------------------------
from django.core.mail.backends.smtp import EmailBackend as DjangoSMTPBackend


class UnverifiedTTLEmailBackend(DjangoSMTPBackend):
    """
    開発用 SMTP バックエンド。
    Django 6 の標準 SMTP バックエンドは settings.EMAIL_SSL_CONTEXT を参照しないため、
    starttls() に渡す ssl_context をここで上書きする。
    """

    @property
    def ssl_context(self):
        if DEBUG:
            return ssl._create_unverified_context()
        if self.ssl_certfile or self.ssl_keyfile:
            ctx = ssl.SSLContext(protocol=ssl.PROTOCOL_TLS_CLIENT)
            ctx.load_cert_chain(self.ssl_certfile, self.ssl_keyfile)
            return ctx
        return ssl.create_default_context()

    def open(self):
        if self.connection:
            return False
        # SMTP ログイン情報は ASCII のみ（UnicodeEncodeError 防止）
        if self.username and not is_ascii_only(str(self.username)):
            raise ValueError("EMAIL_HOST_USER に非ASCII文字が含まれています。")
        if self.password and not is_ascii_only(str(self.password)):
            raise ValueError("EMAIL_HOST_PASSWORD に非ASCII文字が含まれています。")
        return super().open()


EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_USE_BUILTIN_GMAIL = WASE_USE_BUILTIN_GMAIL

(
    EMAIL_HOST_USER,
    EMAIL_HOST_PASSWORD,
    DEFAULT_FROM_EMAIL,
    EMAIL_SMTP_READY,
) = load_sanitized_email_env(
    _env("WASE_EMAIL_HOST_USER"),
    _env("WASE_EMAIL_HOST_PASSWORD"),
    _env("WASE_DEFAULT_FROM_EMAIL"),
)

# DEBUG かつ SMTP 未設定時のみ console へフォールバック（組み込み設定時は常に SMTP）
EMAIL_USE_CONSOLE_FALLBACK = DEBUG and not EMAIL_SMTP_READY

if EMAIL_USE_CONSOLE_FALLBACK:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
elif DEBUG:
    EMAIL_BACKEND = "wasewase.settings.UnverifiedTTLEmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"


def _warn_email_startup() -> None:
    for warning in EMAIL_ENV_WARNINGS:
        print(f"[WASE WARNING] {warning}", file=sys.stderr, flush=True)

    if EMAIL_USE_BUILTIN_GMAIL and EMAIL_SMTP_READY:
        print(
            "[WASE] SMTP 有効: wasewaseofficial@gmail.com / "
            f"backend={EMAIL_BACKEND}",
            file=sys.stderr,
            flush=True,
        )

    if EMAIL_USE_CONSOLE_FALLBACK:
        print(
            "[WASE DEV] Gmail 設定が無効または未設定のため、"
            "認証メールはターミナル（console backend）に出力します。",
            file=sys.stderr,
            flush=True,
        )
    elif DEBUG and "UnverifiedTTLEmailBackend" in EMAIL_BACKEND:
        print(
            "[WASE DEV] UnverifiedTTLEmailBackend: STARTTLS の SSL 証明書検証をスキップします。",
            file=sys.stderr,
            flush=True,
        )
    elif not DEBUG and not EMAIL_SMTP_READY:
        print(
            "[WASE WARNING] 本番モードで Gmail SMTP 設定が不足しています。",
            file=sys.stderr,
            flush=True,
        )


_warn_email_startup()
