"""
Django settings for wasewase project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import ssl
import sys
from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

from .email_env import (
    EMAIL_ENV_WARNINGS,
    WASE_USE_BUILTIN_GMAIL,
    is_ascii_only,
    load_sanitized_email_env,
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DJANGO_DEBUG=(bool, True),
    DATABASE_SSL_REQUIRE=(bool, False),
    SERVE_MEDIA=(bool, True),
    SECURE_SSL_REDIRECT=(bool, False),
    USE_CLOUDINARY=(bool, False),
)

_env_file = BASE_DIR / ".env"
if _env_file.is_file():
    environ.Env.read_env(_env_file)


def _env(name: str, default: str = "") -> str:
    """環境変数を読み込み、前後の空白を除去する。"""
    value = os.environ.get(name, default)
    if value is None:
        return ""
    return str(value).strip()


def _first_env(*names: str, default: str = "") -> str:
    """複数の環境変数名を順に試し、最初に見つかった値を返す。"""
    for name in names:
        value = _env(name)
        if value:
            return value
    return default


def _load_cloudinary_credentials() -> tuple[str, str, str]:
    """
    Cloudinary 認証情報を読み込む。
    正式名（CLOUDINARY_*）に加え、Render で誤設定されがちな短い名前にも対応する。
    """
    cloud_name = _first_env("CLOUDINARY_CLOUD_NAME", "CLOUD_NAME")
    api_key = _first_env("CLOUDINARY_API_KEY", "API_KEY")
    api_secret = _first_env("CLOUDINARY_API_SECRET", "API_SECRET")

    cloudinary_url = _first_env("CLOUDINARY_URL")
    if cloudinary_url.startswith("cloudinary://"):
        without_scheme = cloudinary_url[len("cloudinary://") :]
        if "@" in without_scheme:
            creds, cloud_from_url = without_scheme.rsplit("@", 1)
            if ":" in creds:
                key_from_url, secret_from_url = creds.split(":", 1)
                if not api_key:
                    api_key = key_from_url
                if not api_secret:
                    api_secret = secret_from_url
            if not cloud_name:
                cloud_name = cloud_from_url

    return cloud_name, api_key, api_secret


def _log_media_storage_startup() -> None:
    """起動時にメディア保存先を Render ログへ出力する（秘密情報は出さない）。"""
    backend = STORAGES["default"]["BACKEND"]
    if USE_CLOUDINARY:
        print(
            f"[WASE] Media storage: Cloudinary "
            f"(cloud={CLOUDINARY_CLOUD_NAME}, backend={backend})",
            file=sys.stderr,
            flush=True,
        )
        return

    print(
        f"[WASE] Media storage: local filesystem "
        f"(root={MEDIA_ROOT}, serve_media={SERVE_MEDIA}, backend={backend})",
        file=sys.stderr,
        flush=True,
    )
    if RENDER_EXTERNAL_HOSTNAME:
        print(
            "[WASE WARNING] Render 上でローカルメディア保存です。"
            " 再起動で画像が消えます。USE_CLOUDINARY=True と "
            "CLOUDINARY_CLOUD_NAME / CLOUDINARY_API_KEY / CLOUDINARY_API_SECRET "
            "（または CLOUD_NAME / API_KEY / API_SECRET）を設定してください。",
            file=sys.stderr,
            flush=True,
        )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# 本番（Render）: DJANGO_DEBUG=False
DEBUG = env.bool("DJANGO_DEBUG", default=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("DJANGO_SECRET_KEY", default="")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-n6!_=099v4ai4w#a=h^lvsflew4u7ylh%_bb&7+(7g(cstkpk9"
    else:
        raise ImproperlyConfigured(
            "本番では環境変数 DJANGO_SECRET_KEY を設定してください。"
        )

RENDER_EXTERNAL_HOSTNAME = env("RENDER_EXTERNAL_HOSTNAME", default="")
_allowed_hosts = env("DJANGO_ALLOWED_HOSTS", default="")
if _allowed_hosts:
    if _allowed_hosts.strip() == "*":
        ALLOWED_HOSTS = ["*"]
    else:
        ALLOWED_HOSTS = [
            host.strip() for host in _allowed_hosts.split(",") if host.strip()
        ]
elif RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS = [RENDER_EXTERNAL_HOSTNAME, ".onrender.com"]
elif DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1", "[::1]"]
else:
    # Render 等で未設定の場合のフォールバック（後から DJANGO_ALLOWED_HOSTS で上書き可）
    ALLOWED_HOSTS = ["*"]

_csrf_origins = env("DJANGO_CSRF_TRUSTED_ORIGINS", default="")
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [
        origin.strip() for origin in _csrf_origins.split(",") if origin.strip()
    ]
elif RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS = [f"https://{RENDER_EXTERNAL_HOSTNAME}"]


# ---------------------------------------------------------------------------
# Cloudinary / メディア（INSTALLED_APPS より前に確定させる）
# cloudinary_storage は INSTALLED_APPS に入れない。
# 入れると collectstatic が上書きされ WhiteNoise と衝突してビルドが落ちる。
# メディア保存だけ STORAGES["default"] で MediaCloudinaryStorage を使う。
# ---------------------------------------------------------------------------
CLOUDINARY_CLOUD_NAME, CLOUDINARY_API_KEY, CLOUDINARY_API_SECRET = (
    _load_cloudinary_credentials()
)
_has_cloudinary_credentials = bool(
    CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET
)

_use_cloudinary_raw = os.environ.get("USE_CLOUDINARY")
if _use_cloudinary_raw is not None and str(_use_cloudinary_raw).strip() != "":
    USE_CLOUDINARY = env.bool("USE_CLOUDINARY", default=False)
elif _has_cloudinary_credentials and not DEBUG:
    USE_CLOUDINARY = True
else:
    USE_CLOUDINARY = False

if USE_CLOUDINARY:
    if not _has_cloudinary_credentials:
        raise ImproperlyConfigured(
            "USE_CLOUDINARY=True のときは Cloudinary 認証情報が必要です。"
            " CLOUDINARY_CLOUD_NAME / CLOUDINARY_API_KEY / CLOUDINARY_API_SECRET "
            "（または CLOUD_NAME / API_KEY / API_SECRET、または CLOUDINARY_URL）"
            " を設定してください。"
        )
    import cloudinary

    cloudinary.config(
        cloud_name=CLOUDINARY_CLOUD_NAME,
        api_key=CLOUDINARY_API_KEY,
        api_secret=CLOUDINARY_API_SECRET,
        secure=True,
    )
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": CLOUDINARY_CLOUD_NAME,
        "API_KEY": CLOUDINARY_API_KEY,
        "API_SECRET": CLOUDINARY_API_SECRET,
        "SECURE": True,
    }


# Application definition

AUTH_USER_MODEL = "app.User"

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wasewase.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.notification_badge',
            ],
        },
    },
]

WSGI_APPLICATION = 'wasewase.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASE_URL = env("DATABASE_URL", default="")
if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=env.bool("DATABASE_SSL_REQUIRE", default=False),
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

if USE_CLOUDINARY:
    STORAGES["default"] = {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
    }
    MEDIA_URL = "/media/"
    SERVE_MEDIA = False
else:
    MEDIA_URL = "/media/"
    _media_root = env("MEDIA_ROOT", default="")
    MEDIA_ROOT = Path(_media_root) if _media_root else BASE_DIR / "media"
    SERVE_MEDIA = env.bool("SERVE_MEDIA", default=True)

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)

# ---------------------------------------------------------------------------
# メール（Gmail SMTP）
# wasewase/email_env.py の組み込み設定（wasewaseofficial@gmail.com）が最優先。
# 環境変数 WASE_* は組み込み無効時のみ使用。
# ---------------------------------------------------------------------------
from django.core.mail.backends.smtp import EmailBackend as DjangoSMTPBackend


class UnverifiedTTLEmailBackend(DjangoSMTPBackend):
    """
    開発用 SMTP バックエンド。
    Django 6 の標準 SMTP バックエンドは settings.EMAIL_SSL_CONTEXT を参照しないため、
    starttls() に渡す ssl_context をここで上書きする。
    """

    @property
    def ssl_context(self):
        if DEBUG:
            return ssl._create_unverified_context()
        if self.ssl_certfile or self.ssl_keyfile:
            ctx = ssl.SSLContext(protocol=ssl.PROTOCOL_TLS_CLIENT)
            ctx.load_cert_chain(self.ssl_certfile, self.ssl_keyfile)
            return ctx
        return ssl.create_default_context()

    def open(self):
        if self.connection:
            return False
        if self.username and not is_ascii_only(str(self.username)):
            raise ValueError("EMAIL_HOST_USER に非ASCII文字が含まれています。")
        if self.password and not is_ascii_only(str(self.password)):
            raise ValueError("EMAIL_HOST_PASSWORD に非ASCII文字が含まれています。")
        return super().open()


EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_USE_BUILTIN_GMAIL = WASE_USE_BUILTIN_GMAIL

(
    EMAIL_HOST_USER,
    EMAIL_HOST_PASSWORD,
    DEFAULT_FROM_EMAIL,
    EMAIL_SMTP_READY,
) = load_sanitized_email_env(
    _env("WASE_EMAIL_HOST_USER"),
    _env("WASE_EMAIL_HOST_PASSWORD"),
    _env("WASE_DEFAULT_FROM_EMAIL"),
)

EMAIL_USE_CONSOLE_FALLBACK = DEBUG and not EMAIL_SMTP_READY

if EMAIL_USE_CONSOLE_FALLBACK:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
elif DEBUG:
    EMAIL_BACKEND = "wasewase.settings.UnverifiedTTLEmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"


def _warn_email_startup() -> None:
    for warning in EMAIL_ENV_WARNINGS:
        print(f"[WASE WARNING] {warning}", file=sys.stderr, flush=True)

    if EMAIL_USE_BUILTIN_GMAIL and EMAIL_SMTP_READY:
        print(
            "[WASE] SMTP 有効: wasewaseofficial@gmail.com / "
            f"backend={EMAIL_BACKEND}",
            file=sys.stderr,
            flush=True,
        )

    if EMAIL_USE_CONSOLE_FALLBACK:
        print(
            "[WASE DEV] Gmail 設定が無効または未設定のため、"
            "認証メールはターミナル（console backend）に出力します。",
            file=sys.stderr,
            flush=True,
        )
    elif DEBUG and "UnverifiedTTLEmailBackend" in EMAIL_BACKEND:
        print(
            "[WASE DEV] UnverifiedTTLEmailBackend: STARTTLS の SSL 証明書検証をスキップします。",
            file=sys.stderr,
            flush=True,
        )
    elif not DEBUG and not EMAIL_SMTP_READY:
        print(
            "[WASE WARNING] 本番モードで Gmail SMTP 設定が不足しています。",
            file=sys.stderr,
            flush=True,
        )


_warn_email_startup()

# Django 6 + 旧ライブラリ互換（サードパーティが参照する場合に備える）
STATICFILES_STORAGE = STORAGES["staticfiles"]["BACKEND"]
DEFAULT_FILE_STORAGE = STORAGES["default"]["BACKEND"]

_log_media_storage_startup()
